### PR TITLE
051 dec 13 assessment tracker modals

### LINKED ISSUE #346: Assessment Tracker
Please check the description in the issue #342

### PR DESCRIPTION
**Pull request by MuhammadKhalilzadeh**
## Adding Confirmation Modal (Dialog) for CRUD operations

As earlier discussed, I'm implementing the Modal to confirm before any request other than get is being sent to the BE.

## Issue to close #346 

Mention the issue number(s) this PR addresses (e.g., #123).

Now, there are some other things that are happening slowly beside this pr and up comings as well:

- [x] Hard coded values are being separated
- [x] A new component folder, **vw-v2-components**, is added, which actually is the new version of old components being adapted to new changes like: Being more flexible and having lots of variations, adapted to the upcoming themes that are being implemented, hard-coded values being separated from them.
- [x] A customizable Modal (Dialog) which is customizable in what can be as the content and how its buttons can look like.

## Release Notes

- **New Features**
  - Introduced a confirmation modal for saving assessments.
  - Added a new customizable button component, `VWButton`.
  - Launched a new modal component, `DualButtonModal`, for user interactions.

- **Enhancements**
  - Improved theme flexibility with new button styles and error color definitions.
  - Enhanced user interaction by requiring confirmation before saving assessments.

- **Bug Fixes**
  - Removed unnecessary commented-out code from the Playground component.

- **Style**
  - Added CSS styles for the new `DualButtonModal` component.

### CODE REVIEW

**Comment by MuhammadKhalilzadeh** [comment]
@gorkemcetin 
So far how the new model looks like.
All the text is customizable
The content part can be anything! (text, table, etc.)
Text and the color for both buttons can be changed according to the needs)

Screenshot 2024-12-15 122206

**Comment by MuhammadKhalilzadeh** [comment]
@gorkemcetin 
In the future, all other modals will be replaced with this, making it the most flexible and preventing any repetitions.

**Comment by MuhammadKhalilzadeh** [comment]
Screenshot 2024-12-15 125440

**Comment by gorkem-bwl** [comment]
> @gorkemcetin In the future, all other modals will be replaced with this, making it the most flexible and preventing any repetitions.

I think that was much needed. Flexible and less error prone for everyone. Thanks!

**Pull request merged**
