### PR TITLE
removed hover effect in team's tab/ other tasks in issue already been done 

### PR DESCRIPTION
**Pull request by salmanja**
## Summary by CodeRabbit

- **New Features**
	- Enhanced error handling for the ProfileForm, providing immediate feedback on input validation for first name, last name, and email fields.

- **UI Improvements**
	- Updated formatting for the "Invite team member" and "Save" buttons for consistency and readability.
	- Improved styling for the team member role selection and table layout for enhanced clarity.

- **Bug Fixes**
	- Improved readability of the ProfileForm component without altering functionality.

### CODE REVIEW

**Comment by salmanja** [comment]
https://github.com/user-attachments/assets/94337008-2fde-450c-8d90-3747791e4190

**Comment by MuhammadKhalilzadeh** [comment]
@gorkemcetin Are we done here?

**Comment by MuhammadKhalilzadeh** [comment]
@salmanja 
Please also double check Tab toggles (buttons) as well
Those with name Profile, Password, Team

**Comment by salmanja** [comment]
> @salmanja Please also double check Tab toggles (buttons) as well Those with name Profile, Password, Team

You mean the ones with just a blue underline? all the other buttons dont have a hover effect

**Comment by gorkem-bwl** [comment]
@salmanja Currently when you mouse hover, it doesn't change background color state. Our component should have that state since the end user must see a visual feedback, like making the button's color dark blue. It's in the Figma file already but I don't see it. Is this not in your implementation or not in the component?

**Comment by salmanja** [comment]
> @salmanja Currently when you mouse hover, it doesn't change background color state. Our component should have that state since the end user must see a visual feedback, like making the button's color dark blue. It's in the Figma file already but I don't see it. Is this not in your implementation or not in the component?  

I think Mohammad requested I disable hover effect in the team's tab like the other tab's in the settings page

**Comment by gorkem-bwl** [comment]
He probably requested the "riddle" effect to be removed. As far as I can see, that is removed, which is a good step forward. But we better not remove the visual cue - it's a way to let the user know that the button is there to be clicked on.

**Comment by salmanja** [comment]
> He probably requested the "riddle" effect to be removed. As far as I can see, that is removed, which is a good step forward. But we better not remove the visual cue - it's a way to let the user know that the button is there to be clicked on.

Ok I'll undo it

**Comment by MuhammadKhalilzadeh** [comment]
@salmanja , oh yes, Gorkem's right
Sorry @salmanja , my bad, 💐🌹

AlvinAndTheChipmunksAlvinGIF (2)

I'm getting confused with those lately a lot

**Review by MuhammadKhalilzadeh — APPROVED** [review]

**Pull request merged**
