### PR TITLE
002 nov 15 button group

### PR DESCRIPTION
**Pull request by salmanja**
## Release Notes

- **New Features**
  - Introduced a "File Manager" component for managing and displaying files in a table format.
  - Added a new route for the "File Manager" accessible at `/file-manager`.
  - Updated the sidebar menu to include a "File Manager" entry with an icon.
  - Added a new `RoleButtonGroup` component for role selection with visual feedback.

- **Enhancements**
  - Improved the `BasicTable` component with new interactivity features, including row click handling and enhanced pagination.
  - Added a new "Save" button in the Team settings to save all relevant data at once.

- **Dependency Updates**
  - Updated Material-UI dependencies to their latest versions.

### CODE REVIEW

**Comment by salmanja** [comment]
I'm adding the button group to the Teams page in settings. Still working on it therefore I left it as a comment for now

**Comment by gorkem-bwl** [comment]
Sounds good. You can also add a hover color to the group when the mouse is on hover. You can select a color for this, or I can provide you with the color as well.

**Comment by MuhammadKhalilzadeh** [comment]
1. Please attach your screen shot here
2. Always, always, and always, add reviewers, assignee, label, milestone 😊🔃

**Comment by salmanja** [comment]
Screenshot 2024-11-16 at 7 28 12 PM
Screenshot 2024-11-16 at 7 28 04 PM

finished product, every buttons has a hover effect with blue background color

**Comment by gorkem-bwl** [comment]
- Can you fix the border to 1px, just like how it looks in Figma? 
- Can you double check the radius? (needs to be 8px)
- Can you check the height to be 34px? 

image

**Comment by salmanja** [comment]
> * Can you fix the border to 1px, just like how it looks in Figma?
> * Can you double check the radius? (needs to be 4px)
> * Can you check the height to be 34px?
> 
> image

ok so the border is set to 1 px, i will fix the other suggestions

**Comment by MuhammadKhalilzadeh** [comment]
@salmanja  Always, always, and always, make sure your adding, reviewer, assign, etc.

**Comment by MuhammadKhalilzadeh** [comment]
@salmanja 
Screen shot please

**Comment by gorkem-bwl** [comment]
Can you double check - as it now has two borders?

**Comment by salmanja** [comment]
> Can you double check - as it now has two borders? 

Yes I see, I will fix that

**Comment by salmanja** [comment]
> Can you double check - as it now has two borders?

Screenshot 2024-11-19 at 9 50 04 AM

@gorkem-bwl

**Comment by gorkem-bwl** [comment]
Thanks. Can you double check those ?

1. Border color of the stroke should be same across everywhere
2. The background color should be on par with the Figma design.


image

**Comment by salmanja** [comment]
> Thanks. Can you double check those ?
> 
> 1. Border color of the stroke should be same across everywhere
> 2. The background color should be on par with the Figma design.
> 
> image

Screenshot 2024-11-19 at 10 22 40 AM

**Comment by gorkem-bwl** [comment]
Looks good - thanks. You'll only push the button groups here right? I am not sure what the avatar icons are for.

**Review by gorkem-bwl — APPROVED** [review]

**Comment by salmanja** [comment]
> Looks good - thanks. You'll only push the button groups here right? I am not sure what the avatar icons are for. 

So I put them in the playground page for testing. @gorkem-bwl

**Comment by gorkem-bwl** [comment]
> > Looks good - thanks. You'll only push the button groups here right? I am not sure what the avatar icons are for.
> 
> So I put them in the playground page for testing. @gorkem-bwl

Sounds good!

**Pull request merged**
