### PR TITLE
Getting users data in compliacne tracker control pane

### PR DESCRIPTION
**Pull request by melpsh**
Compliance tracking metadata #244

image

@gorkem-bwl Hi Gorkem I have a question about the roles of the users. 

image

the roles are a bit confusing for me especially because they don't match in the file we have Admin and Editor but in UI we have Approver and Owner. Please take a look at my implementation and let me know if I have to change it.

## Summary by CodeRabbit

- **New Features**
	- Dropdowns now dynamically populate options from fetched user data.
	- Added an optional property `getOptionValue` to enhance value retrieval in select dropdowns.

- **Bug Fixes**
	- Removed unused variable `subControlNumber` from the modal component.

- **Documentation**
	- Updated documentation to reflect the new `getOptionValue` property in the Select component.

### CODE REVIEW

**Comment by gorkem-bwl** [comment]
Sure, let me check this tomorrow and get back to you. There might be a few minor changes here and there regarding user rights.

**Comment by MuhammadKhalilzadeh** [comment]
@melpsh 
Thank you very much for the code. 🙏🏻
This branch has conflicts. ❌
Please resolve them, and then we'll be moving forward with the review process. 🔃

**Comment by gorkem-bwl** [comment]
> the roles are a bit confusing for me especially because they don't match in the file we have Admin and Editor but in UI we have Approver and Owner. Please take a look at my implementation and let me know if I have to change it.

User roles in version 1.0 do not effect the entries in drop down boxes. You'll get a list of all users in the database and the admin will populate those fields. That is the easiest implementation for now and we'll revisit it later.

**Comment by gorkem-bwl** [comment]
Do we have anything to get done here @melpsh ?

**Comment by MuhammadKhalilzadeh** [comment]
@melpsh 
What's your plan for this pr?
Its been here for while now.

**Comment by MuhammadKhalilzadeh** [comment]
@melpsh 
Would you please add screenshot or recording for this?
Let's merge this.

**Review by MuhammadKhalilzadeh — APPROVED** [review]

**Pull request merged**
