### PR TITLE
009 oct 14 profile page team

### PR DESCRIPTION
**Pull request by melpsh**
1- Finalized the team section of the Settings page, ensuring all UI elements are in place.
2- Made minor improvements to the Users page for better consistency and usability.
3- The table functionality in the Team sub-control is not yet implemented. This will be included in the next PR to keep this PR smaller and more manageable for review.

## Summary by CodeRabbit

- **New Features**
	- Introduced a new `ProfilePage` component with a tabbed interface for user settings, including "Users," "Password," and "Team."
	- Added dedicated components for managing password settings, user profile settings, and team settings.
- **Bug Fixes**
	- Updated import paths to reflect the new structure without affecting routing.
- **Chores**
	- Removed the old `ProfilePage` component from the previous settings structure.

### CODE REVIEW

**Comment by melpsh** [comment]
image

**Comment by gorkem-bwl** [comment]
Suggesting a few changes here and there. 

376449028-6e8e5f53-1980-439f-91d3-604817563ae2

**Comment by gorkem-bwl** [comment]
Also fyi - comparison with the table row height in Compliance Tracker page: 

image

**Review by MuhammadKhalilzadeh — CHANGES_REQUESTED** [review]
As mentioned by @gorkem-bwl  there are inconsistencies with the Figma design.
Also keep in mind that in many cases you cam find icons in MUI Icon. In that case you'll have more flexibility to manipulate the design according to ours.

**Review by MuhammadKhalilzadeh — APPROVED** [review]
✅

**Pull request merged**
