### PR TITLE
004 oct 13 project risks view

### PR DESCRIPTION
**Pull request by popovaevgeniya**
Implemented Project Risks View and Vendor Risks View tabs

## Release Notes

- **New Features**
	- Introduced a new `Risks` component to display various risk categories.
	- Added a `RisksView` component for summarizing project risks with a structured table layout.
	- Enhanced the `ProjectView` component to include tabs for project and vendor risks.

- **Improvements**
	- Updated the `BasicTable` to conditionally render icons based on availability.
	- Streamlined the `Overview` component by integrating the `Risks` component for better modularity.
	- Refined the CSS styles for table components, improving visual presentation and spacing.

- **Bug Fixes**
	- Adjusted styling for improved layout and responsiveness in various components.

### CODE REVIEW

**Comment by popovaevgeniya** [comment]
image
image

**Comment by MuhammadKhalilzadeh** [comment]
@popovaevgeniya 
Titles on the table header are not aligned with texts inside the rows.
Also the text color is different.
Please check the code for tables in Vendors and Compliance Tracker pages.

**Comment by MuhammadKhalilzadeh** [comment]
@gorkemcetin 
What do you think about these boxes on the top?
I guess @popovaevgeniya needs to do the same as on the Dashboard right? not being stretched horizontally?

**Review by MuhammadKhalilzadeh — CHANGES_REQUESTED** [review]
🔃

**Comment by gorkem-bwl** [comment]
> @gorkemcetin What do you think about these boxes on the top? I guess @popovaevgeniya needs to do the same as on the Dashboard right? not being stretched horizontally?

Right. Let's make the risk boxes fixed width. Thanks for catching this.

**Comment by gorkem-bwl** [comment]
@popovaevgeniya could you also please a few things here? 

1. Let's make gaps between groups of headers 32px
2. Let's left align the table headers with table rows.

Thank you!

378164087-dc60d0d7-460a-4ce4-a17d-233636ed347c

**Comment by popovaevgeniya** [comment]
> @popovaevgeniya Titles on the table header are not aligned with texts inside the rows. Also the text color is different. Please check the code for tables in Vendors and Compliance Tracker pages.

@MuhammadKhalilzadeh The text color is the same as in Figma. Did we discuss changing it? On Vendors page it does not match the color in Figma.

I fixed the rest.
image
image
image

**Comment by gorkem-bwl** [comment]
> > @popovaevgeniya Titles on the table header are not aligned with texts inside the rows. Also the text color is different. Please check the code for tables in Vendors and Compliance Tracker pages.
> 
> @MuhammadKhalilzadeh The text color is the same as in Figma. Did we discuss changing it? On Vendors page it does not match the color in Figma.

Yep, we discussed it during our last meeting that we're going to match it with the colors in Vendors page. Figma is yet to be modified, unfortunately (shame on me). 

This one looks good, thank you.

**Comment by popovaevgeniya** [comment]
image

**Comment by popovaevgeniya** [comment]
image

**Comment by gorkem-bwl** [comment]
Looks good, thank you.

@MuhammadKhalilzadeh UI-wise we are cool here.

**Review by MuhammadKhalilzadeh — APPROVED** [review]

**Pull request merged**
