### PR TITLE
UI update for team profile section

### PR DESCRIPTION
**Pull request by melpsh**
I’ve updated the changes as requested in [Issue #108](https://github.com/bluewave-labs/verifywise/issues/108).

I’ve resolved all the issues, except for the alignment between the header and the cell content in the "Role" column. Since the cell content is inside a Select component, there’s inherent spacing around the text due to the nature of the Select field. Aligning the text exactly with the header is challenging because the text inside the Select is centered within the field. Do you have any suggestions or ideas on how to best align the text in this case?

@MuhammadKhalilzadeh @gorkemcetin 

## Summary by CodeRabbit

- **New Features**
	- Enhanced visual presentation of the Team settings page with improved table layout.
	- Introduced consistent styling across table components using a new theme.

- **Bug Fixes**
	- Adjusted text alignment and widths for better readability and user interaction.
	- Improved spacing for action buttons and role selection dropdown for a more cohesive look.

- **Documentation**
	- Updated import statements to reflect new components and themes.

### CODE REVIEW

**Comment by melpsh** [comment]
image

**Comment by MuhammadKhalilzadeh** [comment]
@gorkemcetin 
What do you think of this UI wise?
@melpsh Is this the Latest screenshot? or any new modifications is added?

**Comment by gorkem-bwl** [comment]
I believe there will be another screenshot to be attached here, so let's wait for it.

**Comment by melpsh** [comment]
yes here is the screenshot of the latest version:
image

please let me know if you want me to change something.

**Comment by gorkem-bwl** [comment]
Looks good! Thank you.

**Pull request merged**
