### PR TITLE
minor redesigns

### LINKED ISSUE #175: Vendor page minor redesign
There are two small fixes in the vendor page. 

1. When I add a new vendor or edit one (Vendor details tab), the project input should be drop down as the project name should be selected from a list of internal projects.

image

2. When I add a new vendor or edit one (Risks tab), there is no need for the Project name input, as it is already there in the previous tab.

image

### PR DESCRIPTION
**Pull request by MuhammadKhalilzadeh**
Addressing to close #175 

Here are screenshots

What do you think @gorkemcetin ?

Screenshot 2024-11-02 133744

Screenshot 2024-11-02 133757

## Summary by CodeRabbit

- **New Features**
	- Introduced a dropdown selection for project association in the Add New Vendor modal, with options for "Chatbot AI," "Marketing AI," and "Compliance AI."
	- Added a new "Impact" dropdown for selecting risk levels (High, Moderate, Low).

- **Improvements**
	- Streamlined the risksPanel layout for better user experience.
	- Updated risk severity categories to Critical, Major, Minor and risk levels to High, Moderate, Low for clarity.

- **Bug Fixes**
	- Maintained consistent error handling and modal functionality.

### CODE REVIEW

**Comment by gorkem-bwl** [comment]
Good to go when we fix this.

382463990-1ecd1243-ace9-421c-aba8-b82b5bb53a8b

**Review by gorkem-bwl — COMMENTED** [review]
Suggested a minor fix

**Comment by MuhammadKhalilzadeh** [comment]
@gorkem-bwl 
What are the values in px here?

**Comment by gorkem-bwl** [comment]
> @gorkem-bwl What are the values in px here?

If the gap separates two distinct screen elements, it is 16px. 
For the gaps between same screen element groups, it is 8px. 

For this example, the red area is 16px in height, whereas the purple area is 8px in height. 

SCR-20241103-jegb

**Comment by MuhammadKhalilzadeh** [comment]
@gorkem-bwl 
The Latest

Screenshot 2024-11-03 190434

Screenshot 2024-11-03 190455

**Review by gorkem-bwl — APPROVED** [review]

**Pull request merged**
