### PR TITLE
added table pagination

### PR DESCRIPTION
**Pull request by melpsh**
Added pagination for issue #332 

https://github.com/bluewave-labs/verifywise/compare/master...melpsh:verifywise:33-dec-10-table-pagination-in-teams?expand=1

## Summary by CodeRabbit

- **New Features**
	- Introduced pagination functionality in the Team Management component for improved navigation of team members.
	- Added controls for selecting the number of rows displayed per page.

### CODE REVIEW

**Comment by melpsh** [comment]
image

**Review by MuhammadKhalilzadeh — APPROVED** [review]

**Comment by MuhammadKhalilzadeh** [comment]
Hi @melpsh 
thank you for the code 🙏🏻

You had three open pull requests with two of them holding conflicts with the master!
I merged this one to decrease the piled work, but the issue again with this part is:

Where's this pagination coming from?
The looks of it does not match to what we have in components?
Comments for the appearance will be added by @gorkem-bwl soon.

Please, after your conflicts are fixed, created a new branch and modify this pagination!

Regards

**Comment by MuhammadKhalilzadeh** [comment]
@gorkem-bwl 
Would you please create a new issue for @melpsh and list all the details that needs to be fixed here?

**Comment by gorkem-bwl** [comment]
> @gorkem-bwl Would you please create a new issue for @melpsh and list all the details that needs to be fixed here?

Sure. @melpsh let's talk about this one during our call and let me show you a proper pagination from components.

**Pull request merged**
