### PR TITLE
bug fix and enhancements in Alert component

### PR DESCRIPTION
**Pull request by MuhammadKhalilzadeh**
This is how Alert components would look like now:

- Success
- Warning
- Error
- Info

Inconsistencies left from previous project and also bugs in colorings are fixed here. 

Screenshot 2024-10-13 113850

## Release Notes

- **New Features**
  - Introduced a new `/playground` route in the app for testing purposes.
  - Added a new `Playground` component that displays multiple alert variants.

- **Enhancements**
  - Updated the `Alert` component with improved icon mapping and styling adjustments.
  - Enhanced theme configuration with a new color palette and button variant styles.
  - Integrated new alert styles into the theme for better visual consistency.

- **Bug Fixes**
  - Ensured alert components maintain functionality while improving visual representation.

### CODE REVIEW

**Comment by MuhammadKhalilzadeh** [comment]
@gorkemcetin 
What do you think about this?

**Review by gorkem-bwl — CHANGES_REQUESTED** [review]
Let's remove "Dismiss" as we have another dismiss icon on top right.

**Comment by MuhammadKhalilzadeh** [comment]
@gorkem-bwl  Looks better, don't it? 

Screenshot 2024-10-14 084354

**Comment by gorkem-bwl** [comment]
Looks better. Can we have a version where we don't have to enter a header? E.g if the header is nonexistent, it won't show, and only the description/main line will show.

**Comment by MuhammadKhalilzadeh** [comment]
@gorkem-bwl 
Done ✅

this is how it looks now:

Screenshot 2024-10-14 211814

**Review by gorkem-bwl — APPROVED** [review]

**Pull request merged**
