### PR TITLE
Status code Page implemented

### PR DESCRIPTION
**Pull request by melpsh**
Created a dynamic page to receive the status codes to handle.

## Summary by CodeRabbit

- **New Features**
  - Introduced a `StatusCodePage` component to display HTTP status codes and their corresponding messages.
  - Implemented a mapping of HTTP status codes to functions that return structured messages based on the status code.

- **Bug Fixes**
  - Added error handling for invalid status codes, ensuring users receive appropriate feedback.

- **Documentation**
  - Enhanced documentation for the new `StatusCodePage` component and associated status code functionalities.

### CODE REVIEW

**Comment by melpsh** [comment]
Related to Issue #57 : https://github.com/bluewave-labs/verifywise/issues/57

**Comment by gorkem-bwl** [comment]
Can you please send a screenshot? FYI - doesn't have to be complex, just a simple message is enough.

**Comment by melpsh** [comment]
@gorkemcetin  I haven't called this UI anywhere in the code because I didn't find anywhere that this component needs to be called yet. so I just created the component so whenever we need it we can use it. It's just a simple heading and a paragraph that's it, as simple as possible.

**Comment by gorkem-bwl** [comment]
Sounds good!

**Review by MuhammadKhalilzadeh — APPROVED** [review]
✅

**Pull request merged**
