### PR TITLE
Fixed the pagination of the tale in Teams

### PR DESCRIPTION
**Pull request by melpsh**
## Describe your changes

Briefly describe the changes you made and their purpose.

## Summary by CodeRabbit

- **New Features**
	- Enhanced pagination functionality in the Team Management component.
	- Added customizable options for rows per page and improved dropdown styling.

- **Improvements**
	- Integrated context for better management of dashboard values.
	- Simplified rendering and event handling in table cells.

- **Bug Fixes**
	- Adjusted pagination logic for accurate total count.

### CODE REVIEW

**Comment by melpsh** [comment]
image

**Comment by MuhammadKhalilzadeh** [comment]
@gorkemcetin 
What do you think? any modifications you'd desire?

**Comment by gorkem-bwl** [comment]
UI wise looks good to me. We can remove the line over "Save" button. 

Also if there are more than 5 lines, or 10 lines - does it work properly?

**Comment by MuhammadKhalilzadeh** [comment]
That line is I guess a sight shadow from Pagination. But can be fixed easily.
Last time I checked it was working. And its working on other places as well. So, I don't think it would be a problem.

**Comment by gorkem-bwl** [comment]
Thanks for the confirmation - if that line is from the pagination component, then we can leave it as is.

**Review by MuhammadKhalilzadeh — APPROVED** [review]

**Pull request merged**
