### PR TITLE
Fix assessment active menu and display default value for dropdown

### PR DESCRIPTION
**Pull request by eieimon**
## Describe your changes

- Display dropdown default value at sidebar when the page loads
- Fixed active menu issue for assessment tracker menu item at sidebar

## Issue number

Mention the issue number(s) this PR addresses (e.g., #373, #374).

## Please ensure all items are checked off before requesting a review:

- [x] I deployed the code locally.
- [x] I have performed a self-review of my code.
- [x] I have included the issue # in the PR.
- [x] I have labelled the PR correctly.
- [x] The issue I am working on is assigned to me.
- [x] I didn't use any hardcoded values (otherwise it will not scale, and will make it difficult to maintain consistency across the application).
- [x] I made sure font sizes, color choices etc are all referenced from the theme.
- [x] My PR is granular and targeted to one specific feature.
- [x] I took a screenshot or a video and attached to this PR if there is a UI change.

## Summary by CodeRabbit

- **New Features**
	- Enhanced sidebar responsiveness to project selection changes.
	- Improved navigation logic for assessments, redirecting from `/all-assessments` to `/assessment`.

- **Bug Fixes**
	- Clarified the handling of the selected project ID for better state management.

### CODE REVIEW

**Comment by MuhammadKhalilzadeh** [comment]
Hi @eieimon 
Thank you for the nice code 🙏🏻
Congrates on your first pr 🌹😊

Please consider the followings:

- First, always make sure that the configuration for the pull request is set:
Screenshot 2024-12-26 223101

- Also, you've **checked** everything, but there's no screen shots or screen recordings attached.
Screenshot 2024-12-26 223127

It is very important for all of us to know that this checklist is added to make sure that all details are considered. It will be ironic if we also ignore the checklist and just **check** everything just to simple **CHECK** them.

Regards, Mo.

**Comment by eieimon** [comment]
- Display the default dropdown as the index of 1 "All Compliance Checker".
- Display active menu when user clicks on Go-To-Assessments button on the assessment tracker page 

verifywise-UI-changes

**Comment by gorkem-bwl** [comment]
Looks good, thanks.

**Comment by MuhammadKhalilzadeh** [comment]
@eieimon 
Thank you so much 🙏🏻

**Review by MuhammadKhalilzadeh — APPROVED** [review]

**Pull request merged**
