### PR TITLE
Implemented ComplianceTracker Page- first section

### PR DESCRIPTION
**Pull request by melpsh**
I couldn't find the correct icons for the accordion table, so I used placeholder icons for now. I will update them later once I find the correct ones.

## Summary by CodeRabbit

- **New Features**
	- Introduced compliance metrics and details for enhanced tracking.
	- Added a dropdown menu in the Compliance section for project selection, dynamically updating compliance metrics.
	- Implemented an accordion interface for expandable sections on compliance requirements.

- **Refactor**
	- The ComplianceTracker component has been renamed to Compliance and refactored for improved functionality and user interaction.

- **Style**
	- Enhanced layout and presentation using Material-UI components for a more organized and visually appealing interface.
	- Standardized styling for table cells to improve data presentation.

### CODE REVIEW

**Comment by gorkem-bwl** [comment]
@MuhammadKhalilzadeh are we going to use the icons from MUI or will we use the icons from our Style Guide on Figma?

**Comment by MuhammadKhalilzadeh** [comment]
@gorkem-bwl Both of theme, but mainly, we export icons from the Figma design in SVG format in the icons directory.

**Comment by MuhammadKhalilzadeh** [comment]
@melpsh Please upload screenshots your your current looks of the UI.

**Comment by melpsh** [comment]
Hi Mohammad,
here is a screenshot of the page I implemented.
{130B6DF9-13D2-4AAF-B334-A1C0197CA93F}

**Comment by melpsh** [comment]
Also, there is no button associated with SubControlPane in Figma implementation.

{29CAEB45-8EFE-4056-A4E5-AC317CEFA56B}

Please let me know which button is responsible for opening the subControl.
Thank you

**Comment by MuhammadKhalilzadeh** [comment]
@gorkem-bwl Would you please provide more details about how `Subcontrol pane` will be opened in `Compliance Tracker` page?

**Comment by gorkem-bwl** [comment]
> Also, there is no button associated with SubControlPane in Figma implementation.

When I click on a row on the main table, the corresponding subcontrol pane will be opened. When the mouse is over a row, the background color will change to #FCFCFC

**Comment by melpsh** [comment]
@gorkemcetin We'll update the data types once we finalize the structure of the data received from the backend. @MuhammadKhalilzadeh, kindly confirm this pull request if you've already completed your review. Thanks for your attention!

**Comment by gorkem-bwl** [comment]
> @gorkemcetin We'll update the data types once we finalize the structure of the data received from the backend. @MuhammadKhalilzadeh, kindly confirm this pull request if you've already completed your review. Thanks for your attention!

Thank you. I'll work with @Mertcanboyar tomorrow to make sure we finalize the data structure very soon.

**Review by MuhammadKhalilzadeh — APPROVED** [review]
Looks good to me. ✅
Thank you and Nice job 👍🏻

**Pull request merged**
