### PR TITLE
settings modal logic

### PR DESCRIPTION
**Pull request by salmanja**
## Describe your changes

Briefly describe the changes you made and their purpose.

## Issue number

Mention the issue number(s) this PR addresses (e.g., #123).

## Please ensure all items are checked off before requesting a review:

- [x] I deployed the code locally.
- [x] I have performed a self-review of my code.
- [x] I have included the issue # in the PR.
- [x] I have labelled the PR correctly.
- [x] The issue I am working on is assigned to me.
- [x] I didn't use any hardcoded values (otherwise it will not scale, and will make it difficult to maintain consistency across the application).
- [x] I made sure font sizes, color choices etc are all referenced from the theme.
- [x] My PR is granular and targeted to one specific feature.
- [x] I took a screenshot or a video and attached to this PR if there is a UI change.

## Summary by CodeRabbit

- **New Features**
	- Enhanced validation for the ProfileForm, preventing saves with invalid input.
	- User ID is now managed more effectively, improving data handling.
	- Updated API base URL for improved backend connectivity.

- **Bug Fixes**
	- Improved error handling for save failures, providing more descriptive messages.

- **User Experience**
	- The Save button is now disabled when validation errors are present, ensuring users can only proceed with valid input.
	- Streamlined control flow for handling modals related to confirmation and errors.

- **Chores**
	- Updated environment configuration to reflect the new API base URL.
	- Added `.env` to the .gitignore file to prevent sensitive data from being tracked.
	- Bumped the version of the dotenv dependency for better functionality.

### CODE REVIEW

**Comment by salmanja** [comment]
https://github.com/user-attachments/assets/74143de6-8f65-4af5-b604-ba2ca7dd8892

So the backend logic works for @MuhammadKhalilzadeh. However, connecting to the server isnt working for me so im getting connection errors in the console. Now the user cannot save inputs with validaiton errors and the modals are triggered depending on the input fields. The error modal should only display with validation errors when bypassing the handleSave

**Comment by gorkem-bwl** [comment]
> Screen.Recording.2024-12-18.at.2.43.31.PM.mov 
> So the backend logic works for @MuhammadKhalilzadeh. However, connecting to the server isnt working for me so im getting connection errors in the console. Now the user cannot save inputs with validaiton errors and the modals are triggered depending on the input fields. The error modal should only display with validation errors when bypassing the handleSave

Thanks for this. Is there a reason for two-liner error message? Can you fit it in one line so it looks better? 

Also saving this information is not destructive so we can remove the approval popup.

**Comment by salmanja** [comment]
> > Screen.Recording.2024-12-18.at.2.43.31.PM.mov 
> 
> > So the backend logic works for @MuhammadKhalilzadeh. However, connecting to the server isnt working for me so im getting connection errors in the console. Now the user cannot save inputs with validaiton errors and the modals are triggered depending on the input fields. The error modal should only display with validation errors when bypassing the handleSave
> 
> 
> 
> Thanks for this. Is there a reason for two-liner error message? Can you fit it in one line so it looks better? 
> 
> 
> 
> Also saving this information is not destructive so we can remove the approval popup.
> 
> 

You want me to remove the confirmation modal?

**Comment by gorkem-bwl** [comment]
> > 
> > Thanks for this. Is there a reason for two-liner error message? Can you fit it in one line so it looks better?
> > Also saving this information is not destructive so we can remove the approval popup.
> 
> You want me to remove the confirmation modal?

Yes - the confirmation modal there seems to be an extra overhead for the user. 

Also, is it possible to fit the error message in 1 line?

**Comment by salmanja** [comment]
image

Confirmation modal removed. Error modal message is one liner now, bolded, fontsize is 13px.

**Comment by gorkem-bwl** [comment]
> Confirmation modal removed. Error modal message is one liner now, bolded, fontsize is 13px.

The Retry button has a red color. Red is associated with danger and used when removing / deleting something, e.g user or data. Please use a generic button there (think of it similar to a 'Save' button). Background should be filled.

**Comment by salmanja** [comment]
synced the changes @MuhammadKhalilzadeh made in PR 056 dec 17 enhancements

**Comment by salmanja** [comment]
> @salmanja Could you please add a screenshot or recording?


https://github.com/user-attachments/assets/e1d50f46-86d6-4fc6-90dd-f1fad2d83c98

**Review by MuhammadKhalilzadeh — APPROVED** [review]

**Pull request merged**
