### PR TITLE
 file uploader modalization

### PR DESCRIPTION
**Pull request by salmanja**
## Release Notes

- **New Features**
	- Introduced a new file upload component allowing uploads via button click or drag-and-drop.
	- Enhanced file upload management with dynamic display of uploaded files, including error handling and status messages.
	- Added a modal interface for file uploads to improve user experience.

- **Improvements**
	- Improved layout and user interaction for file uploads with new styled components and modal design.
	- Enhanced error handling during file uploads, ensuring better user feedback.
	- Added new styles for a more visually appealing file upload interface.
	- Streamlined the configuration and initialization of the file upload instance for better performance.
	- Added configurability for file types and size limits during uploads.

- **Bug Fixes**
	- Updated error handling to log issues and prevent duplicate file uploads.
	- Removed outdated file upload handling logic for improved functionality.
	- Adjusted the height of the file upload container for better alignment.

### CODE REVIEW

**Comment by salmanja** [comment]
Currently working on displaying uploaded files in the UI and the cancel button. Still making changes and fixing UI

**Comment by salmanja** [comment]
> Currently working on displaying uploaded files in the UI and the cancel button. Still making changes and fixing UI

what the current UI looks like:
Screenshot 2024-12-06 at 3 51 59 AM

**Comment by MuhammadKhalilzadeh** [comment]
@salmanja 
It should not have horizontal scroll

@gorkemcetin What do you think?
And any other details beside that?

**Comment by gorkem-bwl** [comment]
> @salmanja It should not have horizontal scroll
> 
> @gorkemcetin What do you think? And any other details beside that?

I think Jamilah is still working on it so let's see what the final UI looks like. 

@salmanja it's better to post the final UI here to save time for comments.

**Comment by salmanja** [comment]
> > @salmanja It should not have horizontal scroll
> 
> > 
> 
> > @gorkemcetin What do you think? And any other details beside that?
> 
> 
> 
> I think Jamilah is still working on it so let's see what the final UI looks like. 
> 
> 
> 
> @salmanja it's better to post the final UI here to save time for comments.

Yes I will make the changes and upload a video when done

@gorkem-bwl aside from the overflow, what are UI expectations for the uploaded files? As there's no figma design (unless I missed it)

**Comment by gorkem-bwl** [comment]
> @gorkem-bwl aside from the overflow, what are UI expectations for the uploaded files? As there's no figma design (unless I missed it)

Right - you didn't miss as I didn't create them. Basically, the upload dialog screenshot you uploaded above is more than fine. It includes the file name, alongside with a way to remove it (the trash icon). Those are the only requirements for now.

**Comment by salmanja** [comment]
> @salmanja 
> 
> Could you please add an screen shot or screen record?
> 
> Are we done here?

Not done, working on the modal and spinner

**Comment by salmanja** [comment]
Modal is complete, using questions-endpoint-test. Current challenge I need to fix is the upload status bar. There's a default UI that is overlapping my UI. I will be fixing that.

**Comment by salmanja** [comment]
https://github.com/user-attachments/assets/eea23f40-4c59-4e75-8f97-93f6738900c3

**Comment by gorkem-bwl** [comment]
Thanks Jamilah. A few observations: 

1. You can make it a bit wider maybe, to make sure longer file names don't wrap. 
2. There is too much space around the content. You can check other examples in Figma to make it work.
3. There is too narrow gap around "Close" button, again check Figma for examples. 
4. The close button seems to have ripple effect which shouldn't be there. Is it from the components directory? 
 
image

**Comment by MuhammadKhalilzadeh** [comment]
@salmanja 
Thank you so much for the progress.
Please apply required modifications mentioned by @gorkem-bwl 
Then we'll move to the code review

**Comment by salmanja** [comment]
> Thanks Jamilah. A few observations: 
> 
> 
> 
> 1. You can make it a bit wider maybe, to make sure longer file names don't wrap. 
> 
> 2. There is too much space around the content. You can check other examples in Figma to make it work.
> 
> 3. There is too narrow gap around "Close" button, again check Figma for examples. 
> 
> 4. The close button seems to have ripple effect which shouldn't be there. Is it from the components directory? 
> 
>  
> 
> image
> 
> 
> 
> 
> 
> 

Do you mean importing CloseIcon from icons-material? I don't see a close button component. I explored other pages and saw the MUI import

**Comment by gorkem-bwl** [comment]
> 
> Do you mean importing CloseIcon from icons-material? I don't see a close button component. I explored other pages and saw the MUI import

No I mean the Close button (please check the image)

**Comment by salmanja** [comment]
Screenshot 2024-12-12 at 4 15 54 PM

@gorkem-bwl  @MuhammadKhalilzadeh

**Comment by gorkem-bwl** [comment]
@salmanja Let's see how the video looks like so we can have an understanding of the UI/UX in general (please add an example where you upload 6 files at once)

**Comment by gorkem-bwl** [comment]
That looks ok. Do you know why it enlarges in width? (height is ok, but width should have stayed the same as I look at the filenames).

**Comment by salmanja** [comment]
> That looks ok. Do you know why it enlarges in width? (height is ok, but width should have stayed the same as I look at the filenames).


https://github.com/user-attachments/assets/3de03f5c-ce66-4236-9219-f1b3c4564a2d

@gorkem-bwl

**Comment by salmanja** [comment]
> 
> 
> >  Screen.Recording.2024-12-13.at.2.40.18.PM.mov 
> 
> > @gorkem-bwl
> 
> 
> 
> Yes! That is it. Thanks.

No problem 🙏🏼

**Review by MuhammadKhalilzadeh — APPROVED** [review]

**Pull request merged**
